pipeline {
    agent any
    

    stages {
        
        stage('docker login') {
            steps {
                dir('backend') {
                    withDockerRegistry(credentialsId: 'docker-hub-login', url: 'https://index.docker.io/v1/') {
                        sh 'docker build -t nikki1306/3tear-book-store-backend:latest .'
                        sh 'docker push nikki1306/3tear-book-store-backend:latest'
                    }
                }
            }
        }
    }
}
